// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcODJRxrvCbpnk6fTD6xC2xPqGKe70jaw',
    appId: '1:145815930741:android:3eff16842c96870054f53c',
    messagingSenderId: '145815930741',
    projectId: 'fir-chat-982d2',
    storageBucket: 'fir-chat-982d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWw0fmEqLap5l2UPZO08jgQwuJhnCQGfA',
    appId: '1:145815930741:ios:66e64e3e7d38a53854f53c',
    messagingSenderId: '145815930741',
    projectId: 'fir-chat-982d2',
    storageBucket: 'fir-chat-982d2.appspot.com',
    iosBundleId: 'com.firebase.chat.firebaseChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWw0fmEqLap5l2UPZO08jgQwuJhnCQGfA',
    appId: '1:145815930741:ios:8f272781a1e1c47d54f53c',
    messagingSenderId: '145815930741',
    projectId: 'fir-chat-982d2',
    storageBucket: 'fir-chat-982d2.appspot.com',
    iosBundleId: 'com.firebase.chat.firebaseChat.RunnerTests',
  );
}
